version: '3.3'
services:
  vovis:
    # build:
    #   context: .
    #   args:
    #     build_parallel: "-j5"
    image: vovis:xenial
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 1024M
    #   restart_policy:
    #     condition: on-failure
    volumes:
      - ./data:/data
      - ./configs:/configs
    command: /usr/sbin/sshd -D
    ports:
      - "2223:22"
      - "3000:3000"
    networks:
      - vovisnet

networks:
  vovisnet: