version: '3.3'
services:
  vovis:
    # build:
    #   context: .
    #   args:
    #     build_parallel: "-j5"
    image: vovis
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
    volumes:
      - d:/:/data
      - ./configs:/configs
    command: ./VovisRenderer --datasets /configs/datasets.json --configures /configs/configures.json
    ports:
     - "3000:3000"
    networks:
      - vovisnet

networks:
  vovisnet: